database:
  url: sqlite:///clab_topology.db
  echo: false
  pool_pre_ping: true
logging:
  enabled: true
  level: INFO
  format: json
  file_path: null
  max_file_size: 10485760
  backup_count: 5
topology:
  default_prefix: clab
  default_topology_name: generated_lab
  default_mgmt_network: clab
  default_mgmt_subnet: 172.20.20.0/24
  template_path: topology_template.j2
  output_dir: .
bridges:
  bridge_prefix: clab-br
  cleanup_on_exit: false
remote:
  enabled: false
  host: null
  port: 22
  username: null
  password: null
  private_key_path: null
  topology_remote_dir: /tmp/clab-topologies
  timeout: 30
  use_sudo: true
  sudo_password: null
lab:
  current_lab: default
  use_global_database: false
  global_database_path: null
  auto_create_lab: true
node:
  default_username: admin
  default_password: null
  ssh_port: 22
  connection_timeout: 30
  private_key_path: null
debug: false
