# Example configuration file with remote host settings
# Copy this to config.yaml and modify for your environment

# Database settings
database:
  url: "sqlite:///clab_topology.db"
  echo: false
  pool_pre_ping: true

# Logging configuration
logging:
  level: "INFO"
  format: "console"
  file_path: null
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Topology generation settings
topology:
  default_prefix: "clab"
  default_mgmt_network: "clab"
  default_mgmt_subnet: "172.20.20.0/24"
  template_path: "topology_template.j2"
  output_dir: "."

# Bridge management settings
bridges:
  bridge_prefix: "clab-br"
  cleanup_on_exit: false

# Remote host settings (NEW)
remote:
  # Enable/disable remote operations
  enabled: false

  # Remote host connection details
  host: "192.168.1.100"  # Remote containerlab host IP/hostname
  port: 22               # SSH port
  username: "clab-user"  # SSH username

  # Authentication - choose ONE method:
  # Option 1: Password authentication
  password: "your-secure-password"

  # Option 2: SSH key authentication (recommended)
  # private_key_path: "~/.ssh/id_rsa"

  # Remote directories
  topology_remote_dir: "/tmp/clab-topologies"  # Where to upload topology files

  # Sudo configuration for bridge management
  use_sudo: true         # Whether to use sudo for bridge commands (default: true)
  # sudo_password: "sudo-password"  # Sudo password if different from SSH password

  # Connection settings
  timeout: 30  # SSH connection timeout in seconds

# General settings
debug: false
