# Example Local Configuration Override
# Copy this file to config.local.yaml and customize for your local development
#
# Configuration File Discovery Order:
# 1. CLAB_CONFIG_FILE environment variable
# 2. ./clab_tools_files/config.yaml (project-specific)
# 3. ./config.local.yaml (local override)
# 4. Installation directory config.yaml (default)
#
# This file shows all available configuration options with examples

# Database settings - customize for your local environment
database:
  url: "sqlite:///my_local_clab.db"    # Change to your preferred database
  echo: true                           # Enable SQL debugging for development

# Logging settings - customize for your preferences
logging:
  enabled: true                        # Set to false to disable all logging
  level: "DEBUG"                       # Use DEBUG for development, INFO for normal use
  format: "console"                    # Use "console" for development, "json" for production
  # file_path: "/tmp/my_clab.log"      # Uncomment to log to file

# Topology settings - customize for your projects
topology:
  default_prefix: "mydev"              # Change to your name or project identifier
  default_mgmt_network: "mydev"        # Match your prefix
  default_mgmt_subnet: "172.25.0.0/24" # Use a unique subnet to avoid conflicts
  output_dir: "./my_outputs"           # Change output directory if desired

# Bridge settings - customize for your environment
bridges:
  bridge_prefix: "mydev-br"            # Use a unique prefix for your bridges
  cleanup_on_exit: true                # Enable for development (auto-cleanup)

# General settings
debug: true                            # Enable debug mode for development

# Lab settings - customize for your lab workflow
lab:
  current_lab: "dev"                   # Default lab for development
  auto_create_lab: true                # Automatically create lab if it doesn't exist
  use_global_database: false           # Use global database instead of current directory
  global_database_path: null           # Path to global database directory

# Remote host settings - for deploying to remote containerlab hosts
remote:
  enabled: false                       # Enable remote host operations
  host: "192.168.1.100"               # Remote host IP or hostname
  port: 22                            # SSH port
  username: "clab"                     # SSH username
  # password: "password"               # SSH password (not recommended, use keys)
  private_key_path: "~/.ssh/id_rsa"   # SSH private key file path
  topology_remote_dir: "/tmp/clab-topologies"  # Remote directory for topology files
  timeout: 30                          # SSH connection timeout in seconds
  use_sudo: true                       # Use sudo for bridge management commands
  # sudo_password: "sudo_pass"         # Sudo password (if different from SSH password)

# Node settings - for uploading files to individual nodes
node:
  default_username: "admin"            # Default SSH username for nodes
  # default_password: "password"       # Default SSH password (WARNING: plaintext, use keys instead)
  private_key_path: "~/.ssh/id_rsa"   # Default SSH private key for nodes
  ssh_port: 22                         # Default SSH port for nodes
  connection_timeout: 30               # SSH connection timeout in seconds

# Example: Override specific settings for different use cases
#
# For PostgreSQL database:
# database:
#   url: "postgresql://username:password@localhost:5432/my_clab_db"
#   pool_size: 5
#
# For production-like testing:
# logging:
#   level: "INFO"
#   format: "json"
#   file_path: "/tmp/prod_test.log"
# debug: false
#
# For integration testing:
# database:
#   url: "sqlite:///:memory:"  # In-memory database
# logging:
#   level: "WARNING"
#
# For network isolation testing:
# topology:
#   default_mgmt_subnet: "10.200.0.0/16"
# bridges:
#   bridge_prefix: "isolated-br"
