# Clab Tools Configuration File
# YAML configuration for containerlab tools

# Database settings
database:
  # url: "sqlite:///custom_path.db"  # Uncomment to override default package directory location
  echo: false                        # Enable SQL echo for debugging
  pool_pre_ping: true               # Enable connection pool health checks

# Logging settings
logging:
  level: "INFO"                     # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "console"                 # Log format: json, console
  file_path: null                   # Optional log file path
  max_file_size: 10485760          # Max log file size (10MB)
  backup_count: 5                  # Number of backup log files

# Topology generation settings
topology:
  default_prefix: "clab"           # Default topology prefix
  default_topology_name: "homelab" # Default topology name
  default_mgmt_network: "clab"     # Default management network name
  default_mgmt_subnet: "172.20.20.0/24"  # Default management subnet
  template_path: "topology_template.j2"  # Path to Jinja2 template
  output_dir: "."                  # Output directory for generated files

# Lab management settings
lab:
  current_lab: "default"
  use_global_database: false
  global_database_path: null
  auto_create_lab: true

# Bridge management settings
bridges:
  bridge_prefix: "clab-br"         # Prefix for created bridges
  cleanup_on_exit: false           # Auto-cleanup bridges on exit

# General settings
debug: false                       # Enable debug mode globally
