name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        # Install the package in development mode
        pip install -e .

    - name: Run full test suite
      run: |
        pytest tests/ -v --cov=clab_tools --cov-report=term

    - name: Test CLI installation
      run: |
        chmod +x clab-tools.sh
        chmod +x install-cli.sh
        # Install CLI wrapper
        ./install-cli.sh
        # Test basic functionality with new command structure
        clab-tools data import -n example_nodes.csv -c example_connections.csv
        clab-tools data show
        clab-tools topology generate -o release_test.yml --validate

    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release v${{ steps.version.outputs.VERSION }}
        body: |
          ## Changes in v${{ steps.version.outputs.VERSION }}

          This release includes all changes merged to main since the previous release.

          ### Installation
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd clab_homelab_tools
          ./scripts/setup-dev.sh
          ./install-cli.sh
          ```

          ### Usage
          ```bash
          clab-tools --help
          ```

          See the [documentation](docs/) for detailed usage instructions.

        files: |
          clab-tools.sh
          install-cli.sh
        draft: false
        prerelease: false
