name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        # Install the package in development mode
        pip install -e .

    - name: Run full test suite
      run: |
        pytest tests/ -v --cov=clab_tools --cov-report=term

    - name: Test CLI installation
      run: |
        chmod +x clab-tools.sh
        chmod +x install-cli.sh
        # Test basic functionality
        python clab_tools/main.py import-csv -n example_nodes.csv -c example_connections.csv
        python clab_tools/main.py show-data
        python clab_tools/main.py generate-topology -o release_test.yml --validate

    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release v${{ steps.version.outputs.VERSION }}
        body: |
          ## Changes in v${{ steps.version.outputs.VERSION }}

          This release includes all changes merged to main since the previous release.

          ### Installation
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd clab_homelab_tools
          ./scripts/setup-dev.sh
          ./install-cli.sh
          ```

          ### Usage
          ```bash
          clab-tools --help
          ```

          See the [documentation](docs/) for detailed usage instructions.

        files: |
          clab-tools.sh
          install-cli.sh
        draft: false
        prerelease: false
